<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GuruPR.Domain\GuruPR.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.0.1" />
      <PackageReference Include="JetBrains.Annotations" Version="2025.1.0-eap1" />
      <PackageReference Include="Microsoft.SemanticKernel" Version="1.52.0" />
    </ItemGroup>

</Project>
