<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GuruPR.Application\GuruPR.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.1.0-eap1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0-preview.4.25258.110" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.5" />
      <PackageReference Include="Microsoft.SemanticKernel" Version="1.65.0" />
      <PackageReference Include="Microsoft.SemanticKernel.Connectors.HuggingFace" Version="1.52.0-preview" />
      <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.65.0" />
      <PackageReference Include="Microsoft.SemanticKernel.Plugins.Core" Version="1.65.0-preview" />
    </ItemGroup>
    
</Project>
